theme: jekyll-theme-cayman
title: 飘零大帝的博客
brief-intro: Something interesting
description_footer: from Piaolin^Emperor
duoshuo_shortname: #plblog
disqus_shortname: #piaolin

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
