theme: jekyll-theme-cayman
title: 飘零的博客
brief-intro: Something interesting
description_footer: from Piaolin^Emperor
duoshuo_shortname: #plblog
disqus_shortname: #piaolin

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

email:1418676300@qq.com
